[workspace]
members = [
    "crates/world-core",
]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
publish = false

[workspace.dependencies]
blake3 = { version = "1.8.5", default-features = false }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
dbg_macro = "warn"
todo = "warn"
unwrap_used = "warn"
expect_used = "warn"
