[package]
name = "world-standard-runtime"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
world-core = { path = "../world-core" }
world-defs = { path = "../world-defs" }
world-model = { path = "../world-model" }
world-runtime = { path = "../world-runtime" }
world-standard = { path = "../world-standard" }

[lints]
workspace = true
