[package]
name = "world-decision"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
world-core = { path = "../world-core" }
world-defs = { path = "../world-defs" }
world-context = { path = "../world-context" }
thiserror.workspace = true

[lints]
workspace = true
