[package]
name = "world-conformance"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dev-dependencies]
world-authoring = { path = "../world-authoring" }
world-engine = { path = "../world-engine" }
world-standard = { path = "../world-standard" }
world-standard-runtime = { path = "../world-standard-runtime" }

[lints]
workspace = true
